# Generated by Django 5.2.8 on 2025-11-24 19:25

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Donation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('phone_number', models.CharField(max_length=32)),
                ('amount', models.IntegerField(help_text='Amount in major currency unit (e.g. KES/NGN).')),
                ('reference', models.CharField(max_length=100, unique=True)),
                ('status', models.CharField(default='initialized', max_length=32)),
                ('points_awarded', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='donations', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'donations',
                'indexes': [models.Index(fields=['phone_number'], name='donations_phone_n_f528e5_idx'), models.Index(fields=['status'], name='donations_status_14f677_idx')],
            },
        ),
    ]
